Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/a.zhdanov/Desktop/Поделки/ШАД МТС/fastapi_shad_2025/.venv/lib/python3.12/site-packages/uvicorn/__main__.py", line 4, in <module>
    uvicorn.main()
  File "/Users/a.zhdanov/Desktop/Поделки/ШАД МТС/fastapi_shad_2025/.venv/lib/python3.12/site-packages/click/core.py", line 1161, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a.zhdanov/Desktop/Поделки/ШАД МТС/fastapi_shad_2025/.venv/lib/python3.12/site-packages/click/core.py", line 1082, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/Users/a.zhdanov/Desktop/Поделки/ШАД МТС/fastapi_shad_2025/.venv/lib/python3.12/site-packages/click/core.py", line 1443, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a.zhdanov/Desktop/Поделки/ШАД МТС/fastapi_shad_2025/.venv/lib/python3.12/site-packages/click/core.py", line 788, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a.zhdanov/Desktop/Поделки/ШАД МТС/fastapi_shad_2025/.venv/lib/python3.12/site-packages/uvicorn/main.py", line 412, in main
    run(
  File "/Users/a.zhdanov/Desktop/Поделки/ШАД МТС/fastapi_shad_2025/.venv/lib/python3.12/site-packages/uvicorn/main.py", line 579, in run
    server.run()
  File "/Users/a.zhdanov/Desktop/Поделки/ШАД МТС/fastapi_shad_2025/.venv/lib/python3.12/site-packages/uvicorn/server.py", line 66, in run
    return asyncio.run(self.serve(sockets=sockets))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.5/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.5/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "uvloop/loop.pyx", line 1518, in uvloop.loop.Loop.run_until_complete
  File "/Users/a.zhdanov/Desktop/Поделки/ШАД МТС/fastapi_shad_2025/.venv/lib/python3.12/site-packages/uvicorn/server.py", line 70, in serve
    await self._serve(sockets)
  File "/Users/a.zhdanov/Desktop/Поделки/ШАД МТС/fastapi_shad_2025/.venv/lib/python3.12/site-packages/uvicorn/server.py", line 77, in _serve
    config.load()
  File "/Users/a.zhdanov/Desktop/Поделки/ШАД МТС/fastapi_shad_2025/.venv/lib/python3.12/site-packages/uvicorn/config.py", line 435, in load
    self.loaded_app = import_from_string(self.app)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a.zhdanov/Desktop/Поделки/ШАД МТС/fastapi_shad_2025/.venv/lib/python3.12/site-packages/uvicorn/importer.py", line 22, in import_from_string
    raise exc from None
  File "/Users/a.zhdanov/Desktop/Поделки/ШАД МТС/fastapi_shad_2025/.venv/lib/python3.12/site-packages/uvicorn/importer.py", line 19, in import_from_string
    module = importlib.import_module(module_str)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.5/Frameworks/Python.framework/Versions/3.12/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/Users/a.zhdanov/Desktop/Поделки/ШАД МТС/fastapi_shad_2025/src/main.py", line 6, in <module>
    from routers import v1_router
  File "/Users/a.zhdanov/Desktop/Поделки/ШАД МТС/fastapi_shad_2025/src/routers/__init__.py", line 3, in <module>
    from .v1.books import books_router
  File "/Users/a.zhdanov/Desktop/Поделки/ШАД МТС/fastapi_shad_2025/src/routers/v1/books.py", line 9, in <module>
    from src.models.books import Book
ModuleNotFoundError: No module named 'src'
